[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "llama-agents"
version = "0.0.9"
description = ""
authors = ["Logan Markewich <logan.markewich@live.com>", "Andrei Fajardo <andrei@runllama.ai>"]
maintainers = [
  "Logan Markewich <logan@llamaindex.ai>",
  "Andrei Fajardo <andrei@runllama.ai>",
  "Jerry Liu <jerry@llamaindex.ai>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
fastapi = "^0.109.1"
llama-index-core = "^0.10.50"
pytest-asyncio = "^0.23.7"
textual = "^0.70.0"
aio-pika = {version = "^9.4.2", optional = true}
redis = {version = "^5.0.7", optional = true}
uvicorn = "^0.30.1"

[tool.poetry.extras]
rabbitmq = ["aio-pika"]
redis = ["redis"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.4.7"
mypy = "^1.10.0"
aio-pika = "^9.4.2"
redis = "^5.0.7"

[tool.poetry.scripts]
llama-agents = 'llama_agents.cli.command_line:main'
