[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "llama-deploy"
version = "0.1.2"
description = ""
authors = ["Logan Markewich <logan.markewich@live.com>", "Andrei Fajardo <andrei@runllama.ai>"]
maintainers = [
  "Logan Markewich <logan@llamaindex.ai>",
  "Andrei Fajardo <andrei@runllama.ai>",
  "Jerry Liu <jerry@llamaindex.ai>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
fastapi = ">=0.109.1"
llama-index-core = "^0.11.0"
pytest-asyncio = "^0.23.7"
aio-pika = {version = "^9.4.2", optional = true}
redis = {version = "^5.0.7", optional = true}
uvicorn = ">=0.12.0"
pytest-mock = "^3.14.0"
aiokafka = {version = "^0.11.0", optional = true}
kafka-python-ng = {version = "^2.2.2", optional = true}
pydantic-settings = ">=2.0,<3.0"

[tool.poetry.extras]
kafka = ["aiokafka", "kafka-python-ng"]
rabbitmq = ["aio-pika"]
redis = ["redis"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
ruff = "^0.4.7"
mypy = "^1.10.0"
aio-pika = "^9.4.2"
redis = "^5.0.7"
pytest-cov = "^5.0.0"
coverage = "^7.6.0"
aiokafka = "^0.11.0"
kafka-python-ng = "^2.2.2"
