---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: llama-agents-demo

---
apiVersion: v1
data:
  MESSAGE_QUEUE_HOST: "message-queue"
  MESSAGE_QUEUE_PORT: "8000"
  CONTROL_PLANE_HOST: "control-plane"
  CONTROL_PLANE_PORT: "8000"
  SECRET_AGENT_HOST: "secret-agent"
  SECRET_AGENT_PORT: "8000"
  FUNNY_AGENT_HOST: "funny-agent"
  FUNNY_AGENT_PORT: "8000"
  HUMAN_CONSUMER_HOST: "human-consumer"
  HUMAN_CONSUMER_PORT: "8000"
kind: ConfigMap
metadata:
  name: xcore-config
  namespace: llama-agents-demo
