apiVersion: batch/v1
kind: Job
metadata:
  name: control-plane-registration
  namespace: llama-agents-demo
spec:
  template:
    spec:
      containers:
        - name: control-plane-registration
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_NODE_PORT
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_DEFAULT_PASS
            - name: CONTROL_PLANE_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_HOST
            - name: CONTROL_PLANE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xcore-secret
                  key: OPENAI_API_KEY
          image: multi_agent_app:latest
          imagePullPolicy: Never
          command:
            [
              "/bin/sh",
              "-c",
              "python",
              "-m",
              "multi_agent_app.core_services.control_plane",
            ]
      restartPolicy: Never
  backoffLimit: 4
