apiVersion: batch/v1
kind: Job
metadata:
  name: human-consumer-registration
  namespace: llama-agents-demo
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-control-plane
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nslookup control-plane.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]
      containers:
        - name: human-consumer-registration
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_NODE_PORT
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: RABBITMQ_DEFAULT_PASS
            - name: CONTROL_PLANE_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_HOST
            - name: CONTROL_PLANE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_PORT
            - name: HUMAN_CONSUMER_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: HUMAN_CONSUMER_HOST
            - name: HUMAN_CONSUMER_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: HUMAN_CONSUMER_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xcore-secret
                  key: OPENAI_API_KEY
          image: multi_agent_app:latest
          imagePullPolicy: Never
          command:
            [
              "/bin/sh",
              "-c",
              "python",
              "-m",
              "multi_agent_app.additional_services.human_consumer",
            ]
      restartPolicy: Never
  backoffLimit: 4
