apiVersion: batch/v1
kind: Job
metadata:
  name: registration
  namespace: llama-agents-demo
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-message-queue
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nslookup message-queue.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]
        - name: wait-for-control-plane
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nslookup control-plane.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done",
            ]
      containers:
        - name: registration
          env:
            - name: MESSAGE_QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: MESSAGE_QUEUE_HOST
            - name: MESSAGE_QUEUE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: MESSAGE_QUEUE_PORT
            - name: CONTROL_PLANE_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_HOST
            - name: CONTROL_PLANE_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: CONTROL_PLANE_PORT
            - name: SECRET_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: SECRET_AGENT_HOST
            - name: SECRET_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: SECRET_AGENT_PORT
            - name: FUNNY_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: FUNNY_AGENT_HOST
            - name: FUNNY_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: FUNNY_AGENT_PORT
            - name: HUMAN_CONSUMER_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: HUMAN_CONSUMER_HOST
            - name: HUMAN_CONSUMER_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: HUMAN_CONSUMER_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xcore-secret
                  key: OPENAI_API_KEY
          image: multi_agent_app:latest
          imagePullPolicy: Never
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              python -m multi_agent_app.core_services.control_plane &&
              python -m multi_agent_app.agent_services.secret_agent &&
              python -m multi_agent_app.agent_services.funny_agent &&
              python -m multi_agent_app.additional_services.human_consumer
      restartPolicy: Never
  backoffLimit: 4
